# Generated by Django 4.2.4 on 2023-08-28 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_topic_room_host_messages_room_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
