# Generated by Django 4.2.4 on 2023-08-30 12:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0007_alter_profile_options_alter_room_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='profiles',
            field=models.ManyToManyField(related_name='profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
